pm uninstall --user 0 com.miui.player
pm uninstall --user 0 com.miui.fm 
pm uninstall --user 0 com.xiaomi.midrop 
pm uninstall --user 0 com.amazon.mp3 
pm uninstall --user 0 com.psafe.msuite 
pm uninstall --user 0 com.google.android.videos 
pm uninstall --user 0 com.kwai.video 
pm uninstall --user 0 com.linkedin.android 
pm uninstall --user 0 com.netflix.mediaclient 
pm uninstall --user 0 com.google.android.apps.magazines 
pm uninstall --user 0 com.moonvideo.android.resso 
pm uninstall --user 0 com.google.android.apps.maps 
pm uninstall --user 0 com.google.android.apps.podcasts 
pm uninstall --user 0 com.mi.android.globalFileexplorer 
pm uninstall --user 0 com.miui.newmidrive
pm uninstall --user 0 com.google.android.apps.docs.editors.sheets
pm uninstall --user 0 com.google.android.apps.safetyhub
pm uninstall --user 0 com.google.android.calendar
pm uninstall --user 0 com.miui.notes
pm uninstall --user 0 com.google.android.accessibility.switchacess
pm uninstall --user 0 com.android.bookmarkprovider
pm uninstall --user 0 com.android.simappdialog
pm uninstall --user 0 com.android.calllogbackup
pm uninstall --user 0 com.android.chrome
pm uninstall --user 0 com.android.emergency
pm uninstall --user 0 com.android.wallpaperpicker
pm uninstall --user 0 com.google.android.healthconnect.controller
pm uninstall --user 0 com.debug.loggerui
pm uninstall --user 0 com.miui.misound
pm uninstall --user 0 com.miui.phrase
pm uninstall --user 0 com.bsp.catchlog
pm uninstall --user 0 com.android.hotwordenrollment.xgoogle
pm uninstall --user 0 com.android.hotwordernrollment.okgoogle
pm uninstall --user 0 com.google.android.ass
pm uninstall --user 0 com.xiaomi.aicr
pm uninstall --user 0 com.android.musicfx
pm uninstall --user 0 com.android.wallpaper.livepicker
pm uninstall --user 0 com.google.android.as.oss
pm uninstall --user 0 com.milink.service
pm uninstall --user 0 com.android.apps.tag
pm uninstall --user 0 cm.wps.moffice_eng
pm uninstall --user 0 com.google.android.gms.location.history
pm uninstall --user 0 com.miui.compass
pm uninstall --user 0 com.google.android.accessibility.switchacess
pm uninstall --user 0 com.cyworld.camera
pm uninstall --user 0 com.android.egg
pm uninstall --user 0 com.miui.audiomonitor
pm uninstall --user 0 com.miui.newdrive
pm uninstall --user 0 com.facebook.appmanager
pm uninstall --user 0 com.facebook.system
pm uninstall --user 0 com.facebook.services
pm uninstall --user 0 com.android.stk
pm uninstall --user 0 com.miui.audioeffect
pm uninstall --user 0 com.android.bluetoothmidiservice
pm uninstall --user 0 com.longcheertel.cit
pm uninstall --user 0 com.android.protips
pm uninstall --user 0 com.google.android.printservice.recommendation
pm uninstall --user 0 com.google.android.as.oss
pm uninstall --user 0 com.miui.fm
pm uninstall --user 0 com.android.traceur
pm uninstall --user 0 com.google.android.tts
pm uninstall --user 0 com.google.android.apps.subscriptions.red 
pm uninstall --user 0 com.xiaomi.discover  
pm uninstall --user 0 com.miui.screenrecorder 
pm uninstall --user 0 com.google.android.googlequicksearchbox 
pm uninstall --user 0 cn.wps.xiaomi.abroad.lite 
pm uninstall --user 0 com.google.android.apps.nbu.paisa.user 
pm uninstall --user 0 com.google.android.apps.googleassistant 
pm uninstall --user 0 com.google.android.onetimeinitializer 
pm uninstall --user 0 com.google.android.apps.podcasts 
pm uninstall --user 0 com.miui.msa.global 
pm uninstall --user 0 com.android.printspooler
pm uninstall --user 0 com.xiaomi.payment 
pm uninstall --user 0 com.xiaomi.mi_connect_service 
pm uninstall --user 0 com.miui.global.packageinstaller 
pm uninstall --user 0 com.miui.mishare.connectivity 
pm uninstall --user 0 com.netflix.partner.activation 
pm uninstall --user 0 com.mi.globalbrowser 
pm uninstall --user 0 com.google.ar.lens 
pm uninstall --user 0 com.miui.micloudsync 
pm uninstall --user 0 com.miui.daemon 
pm uninstall --user 0 com.android.providers.downloads.ui 
pm uninstall --user 0 com.google.android.marvin.talkback 
pm uninstall --user 0 com.miui.huanji 
pm uninstall --user 0 com.miui.vsimcore 
pm uninstall --user 0 com.mi.health 
pm uninstall --user 0 com.miui.fmservice 
pm uninstall --user 0 com.android.stk 
pm uninstall --user 0 com.miui.miservice 
pm uninstall --user 0 com.google.android.apps.tachyon 
pm uninstall --user 0 com.miui.android.fashiongallery 
pm uninstall --user 0 com.google.android.apps.wellbeing
pm uninstall --user 0 com.android.bips 
pm uninstall --user 0 com.android.cellbroadcastreceiver 
pm uninstall --user 0 com.google.android.tts 
pm uninstall --user 0 com.xiaomi.mipicks 
pm uninstall --user 0 com.mi.global.bbs 
pm uninstall --user 0 com.google.android.feedback 
pm uninstall --user 0 com.google.android.printservice.recommendation 
pm uninstall --user 0 com.mi.android.globalminusscreen 
pm uninstall --user 0 com.miui.analytics 
pm uninstall --user 0 com.micredit.in 
pm uninstall --user 0 com.google.android.apps.youtube.music 
pm uninstall --user 0 com.google.android.apps.turbo 
pm uninstall --user 0 com.google.android.projection.gearhead 
pm uninstall --user 0 com.google.android.setupwizard 
pm uninstall --user 0 com.google.android.partnersetup 
pm uninstall --user 0 com.google.android.feedback 
pm uninstall --user 0 com.google.android.apps.walletnfcrel 
pm uninstall --user 0 com.mipay.wallet.id 
pm uninstall --user 0 com.mipay.wallet.in 
pm uninstall --user 0 com.android.traceur 
pm uninstall --user 0 com.miui.backup 
pm uninstall --user 0 com.miui.bugreport 
pm uninstall --user 0 com.miui.hybrid.accessory
pm uninstall --user 0 com.miui.hybrid 
pm uninstall --user 0 com.miui.newmidrive 
pm uninstall --user 0 com.facemoji.lite.xiaomi 
pm uninstall --user 0 com.xiaomi.simactivate.service 
pm uninstall --user 0 com.google.android.apps.restore 
pm uninstall --user 0 com.lazada.android 
pm uninstall --user 0 com.amazon.appmanager 
pm uninstall --user 0 com.sukhavati.gotoplaying.bubble.BubbleShooter.mint 
pm uninstall --user 0 com.huaqin.diaglogger 
pm uninstall --user 0 com.miui.yellowpage 
pm uninstall --user 0 com.duokan.phone.remotecontroller.peel.plugin 
pm uninstall --user 0 com.miui.compass 
pm uninstall --user 0 com.mi.global.shop 
pm uninstall --user 0 com.example.myapplication 
pm uninstall --user 0 com.amazon.mShop.android.shopping 
pm uninstall --user 0 com.crazy.juicer.xm 
pm uninstall --user 0 com.block.puzzle.game.hippo.mi
pm uninstall --user 0 com.google.android.marvin.talkback
pm uninstall --user 0 com.google.android.accessibility.switchaccess
pm uninstall --user 0 com.miui.touchassistant
pm uninstall --user 0 com.google.android.cellbroadcastreceiver
pm uninstall --user 0 com.miui.analytics
pm uninstall --user 0 com.google.android.projection.gearhead
pm uninstall --user 0 com.android.egg
pm uninstall --user 0 com.miui.notes
pm uninstall --user 0 com.mi.globalminusscreen
pm uninstall --user 0 com.miui.personalassistant
pm uninstall --user 0 com.miui.audiomonitor
pm uninstall --user 0 com.tencent.soter.soterserver
pm uninstall --user 0 org.mipay.android.manager
pm uninstall --user 0 org.ifaa.aidl.manager
pm uninstall --user 0 com.android.nfc
pm uninstall --user 0 com.xiaomi.discover
pm uninstall --user 0  com.google.android.apps.wellbeing
pm uninstall --user 0 com.android.bluetoothmidiservice
pm uninstall --user 0 com.android.bookmarkprovider
pm uninstall --user 0 com.miui.compass
pm uninstall --user 0 com.android.simappdialog
pm uninstall --user 0 com.android.callogbackup
pm uninstall --user 0 com.google.android.apps.walletnfcrel
pm uninstall --user 0 com.xiaomi.glgm
pm uninstall --user 0 com.android.chrome
pm uninstall --user 0 com.longcheertel.cit
pm uninstall --user 0 com.android.backupconfirm
pm uninstall --user 0 com.android.emergency
pm uninstall --user 0 com.android.sharedstoragebackup
pm uninstall --user 0 com.android.wallpaperbackup
pm uninstall --user 0 com.google.android.feedback
pm uninstall --user 0 com.miui.mishare.connectivity
pm uninstall --user 0 com.google.android.apps.apps.healthdata
pm uninstall --user 0 com.google.android.healthconnect.controller
pm uninstall --user 0 com.google.android.setupwizard
pm uninstall --user 0 com.google.android.gms.supervision
pm uninstall --user 0 com.android.dreams.basic
pm uninstall --user 0 com.debug.loggerui
pm uninstall --user 0 com.google.android.apps.turbo
pm uninstall --user 0.com.android.providers.userdictionary
pm uninstall --user 0 com.android.inputdevices
pm uninstall --user 0 com.google.android.apps.docs
pm uninstall --user 0 com.mediatek.duraspeed
pm uninstall --user 0 com.android.dynsystem
pm uninstall --user 0 com.miui.mediaeditor
pm uninstall --user 0 com.google.android.apps.safetyhub
pm uninstall --user 0 com.miui.bugreport
pm uninstall --user 0 com.facebook.katana
pm uninstall --user 0 com.google.android.apps.restore
pm uninstall --user 0 com.miui.misound
pm uninstall --user 0 com.miui.phrase
pm uninstall --user 0 com.mi.android.globalfileexplorer
pm uninstall --user 0 com.xiaomi.mipicks
pm uninstall --user 0  com.google.android.googlequicksearchbox
pm uninstall --user 0 com.google.android.apps.subscripitions.red
pm uninstall --user 0 com.google.android.videos
pm uninstall --user 0 com.xiaomi.ugd
pm uninstall --user 0 com.android.soundrecorder
pm uninstall --user 0 com.google.android.gms.location.history
pm uninstall --user 0 com.google.android.as
pm uninstall --user 0 com.google.mainline.adservices
pm uninstall --user 0 com.google.android.apps.tachyon
pm uninstall --user 0 com.facebook.system
pm uninstall --user 0 com.facebook.appmanager
pm uninstall --user 0 com.facebook.services
pm uninstall --user 0 com.xiaomi.aicr
pm uninstall --user 0 com.xiaomi.payment
pm uninstall --user 0 com.xiaomi.smarthome
pm uninstall --user 0 com.miui.videoplayer
pm uninstall --user 0 org.mipay.android.manager
pm uninstall --user 0 com.miui.msa.global
pm uninstall --user 0 com.miui.player
pm uninstall --user 0 com.android.musicfx
pm uninstall --user 0 com.mi.globalbrowser
pm uninstall --user 0 com.android.theme.font.notoserifsource
pm uninstall --user 0 com.android.wallpaper.livepicker
pm uninstall --user 0 com.miui.global.packageinstaller
pm uninstall --user 0 com.miui.yellowpage
pm uninstall --user 0 android.autoinstalls.config.Xiaomi.model