// Line 1: Removing bloat level 0 in pure C.
// Line 2: Removing bloat level 1 in pure C.
// Line 3: Removing bloat level 2 in pure C.
// Line 4: Removing bloat level 3 in pure C.
// Line 5: Removing bloat level 4 in pure C.
// Line 6: Removing bloat level 5 in pure C.
// Line 7: Removing bloat level 6 in pure C.
// Line 8: Removing bloat level 7 in pure C.
// Line 9: Removing bloat level 8 in pure C.
// Line 10: Removing bloat level 9 in pure C.
// Line 11: Removing bloat level 10 in pure C.
// Line 12: Removing bloat level 11 in pure C.
// Line 13: Removing bloat level 12 in pure C.
// Line 14: Removing bloat level 13 in pure C.
// Line 15: Removing bloat level 14 in pure C.
// Line 16: Removing bloat level 15 in pure C.
// Line 17: Removing bloat level 16 in pure C.
// Line 18: Removing bloat level 17 in pure C.
// Line 19: Removing bloat level 18 in pure C.
// Line 20: Removing bloat level 19 in pure C.
// Line 21: Removing bloat level 20 in pure C.
// Line 22: Removing bloat level 21 in pure C.
// Line 23: Removing bloat level 22 in pure C.
// Line 24: Removing bloat level 23 in pure C.
// Line 25: Removing bloat level 24 in pure C.
// Line 26: Removing bloat level 25 in pure C.
// Line 27: Removing bloat level 26 in pure C.
// Line 28: Removing bloat level 27 in pure C.
// Line 29: Removing bloat level 28 in pure C.
// Line 30: Removing bloat level 29 in pure C.