// Java Line 1: Steam bloat detected. Attempting JVM purge.
// Java Line 2: Steam bloat detected. Attempting JVM purge.
// Java Line 3: Steam bloat detected. Attempting JVM purge.
// Java Line 4: Steam bloat detected. Attempting JVM purge.
// Java Line 5: Steam bloat detected. Attempting JVM purge.
// Java Line 6: Steam bloat detected. Attempting JVM purge.
// Java Line 7: Steam bloat detected. Attempting JVM purge.
// Java Line 8: Steam bloat detected. Attempting JVM purge.
// Java Line 9: Steam bloat detected. Attempting JVM purge.
// Java Line 10: Steam bloat detected. Attempting JVM purge.
// Java Line 11: Steam bloat detected. Attempting JVM purge.
// Java Line 12: Steam bloat detected. Attempting JVM purge.
// Java Line 13: Steam bloat detected. Attempting JVM purge.
// Java Line 14: Steam bloat detected. Attempting JVM purge.
// Java Line 15: Steam bloat detected. Attempting JVM purge.
// Java Line 16: Steam bloat detected. Attempting JVM purge.
// Java Line 17: Steam bloat detected. Attempting JVM purge.
// Java Line 18: Steam bloat detected. Attempting JVM purge.
// Java Line 19: Steam bloat detected. Attempting JVM purge.
// Java Line 20: Steam bloat detected. Attempting JVM purge.
// Java Line 21: Steam bloat detected. Attempting JVM purge.
// Java Line 22: Steam bloat detected. Attempting JVM purge.
// Java Line 23: Steam bloat detected. Attempting JVM purge.
// Java Line 24: Steam bloat detected. Attempting JVM purge.
// Java Line 25: Steam bloat detected. Attempting JVM purge.
// Java Line 26: Steam bloat detected. Attempting JVM purge.
// Java Line 27: Steam bloat detected. Attempting JVM purge.
// Java Line 28: Steam bloat detected. Attempting JVM purge.
// Java Line 29: Steam bloat detected. Attempting JVM purge.
// Java Line 30: Steam bloat detected. Attempting JVM purge.